#!/bin/bash

# Get event messages for newest Cloudwatch stream from provided Cloudwatch event log
# Only works for lambdas prefixed with /aws/lambda/

# Usage: get-log <function name> <aws region>
# Example: get-log myLambda us-east-1

FUNCTION_NAME=$1
REGION=$2

if [[ $REGION = '' ]]; then
  REGION='us-east-1'
fi

LOG_STREAM=$(
  aws logs describe-log-streams \
    --log-group-name /aws/lambda/$FUNCTION_NAME \
    --order-by LastEventTime \
    --descending \
    --max-items 1 \
    --region $REGION \
    --query 'logStreams[0].logStreamName' \
      | tr -d '"'
)

aws logs get-log-events --log-group-name /aws/lambda/$1 --log-stream-name $LOG_STREAM --region $REGION \
    | grep message \
    | sed 's/.*"message": "//' \
    | sed 's/"$//' \
    | sed 's/\\t/ /g' \
    | sed 's/\\n//g' \
    | sed G \
    | sed 's/\\"/"/g'

#aws logs get-log-events --log-group-name /aws/lambda/$1 --log-stream-name $LOG_STREAM --region $REGION \
#    | grep message \
#    | sed 's/.*"message": "//' \
#    | sed 's/"$//' \
#    | sed 's/\\t/ /g' \
#    | sed 's/\\n//g' \
#    | sed G \
#    | sed 's/\\"/"/g'
#
